### PR TITLE
Additonal Fixes to download URLs

### PR DESCRIPTION
**Pull request by tielur**
XML could contains carriage or line breaks as well.

### CODE REVIEW

**Comment by HakanL** [comment]
Are you sure that's necessary, string.Trim calls char.IsWhitespace and according to this page:
http://msdn.microsoft.com/en-us/library/t809ektx.aspx
CRLF is considered whitespace and will be removed.

**Comment by tielur** [comment]
Ahh that's interesting, there's literally TONS of articles on stackoverflow.com asking about how to trim /n, /r, ect.. characters and almost all of them don't mention that. In that case it looks like the Trim call works fine then!

**Comment by HakanL** [comment]
I didn't actually test it with Trim, but I was already under the impression that it would handle it, the link to IsWhitespace was just to confirm what I thought.

**Comment by tielur** [comment]
I just tested it, it works fine! :)

**Comment by HakanL** [comment]
Hehe, I just started VS too. Ok, great! I'm closing this pull request then ;) See you tomorrow!

**Pull request closed without merging**
